import{a as L,i as b,S as v}from"./assets/vendor-CMB7Fqvg.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))o(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const u of s.addedNodes)u.tagName==="LINK"&&u.rel==="modulepreload"&&o(u)}).observe(document,{childList:!0,subtree:!0});function a(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function o(e){if(e.ep)return;e.ep=!0;const s=a(e);fetch(e.href,s)}})();const h=(r,t)=>{const a={params:{q:r,page:t,per_page:15,key:"48292364-ad13d53928d4b39a49844bb07"}};return L.get("https://pixabay.com/api/",a)},p=r=>`
        <li class="gallery-card">
            <a href="${r.largeImageURL}">
                <img src="${r.webformatURL}" alt="${r.tags}"/>
            </a>
            <div class="info">
                <p>Likes: ${r.likes}</p>
                <p>Views: ${r.views}</p>
                <p>Comments: ${r.comments}</p>
                <p>Downloads: ${r.downloads}</p>
            </div>
        </li>`,i=r=>{b.show({title:"❌",message:r,position:"topRight",timeout:3e3})},g=document.querySelector(".form"),l=document.querySelector(".search-list"),d=document.querySelector(".js-btn-load"),m=document.querySelector(".loader");let n=1,c="",y=0;const f=new v(".gallery-card a",{captionDelay:250,captionsData:"alt"}),w=async r=>{if(r.preventDefault(),c=r.currentTarget.elements.search.value.trim(),c===""){i("Enter text to search!");return}n=1,m.classList.add("active"),d.classList.add("is-hidden");try{const{data:t}=await h(c,n);if(t.hits.length===0){i("Sorry, there are no images matching your search query. Please try again!"),l.innerHTML="",g.reset();return}y=Math.ceil(t.totalHits/15);const a=t.hits.map(o=>p(o)).join("");l.innerHTML=a,t.totalHits>15&&d.classList.remove("is-hidden"),f.refresh()}catch(t){console.log(t),i("Something went wrong. Please try again later.")}finally{m.classList.remove("active")}};g.addEventListener("submit",w);const S=async r=>{try{n++;const{data:t}=await h(c,n);if(t.hits.length===0||n>=y){d.classList.add("is-hidden"),i("We're sorry, but you've reached the end of search results.");return}const a=t.hits.map(e=>p(e)).join("");l.insertAdjacentHTML("beforeend",a),f.refresh();const o=l.querySelector(".gallery-card");if(o){const e=o.getBoundingClientRect().height;window.scrollBy({top:e*2,behavior:"smooth"})}}catch(t){console.log(t),i("Something went wrong. Please try again later.")}finally{m.classList.remove("active")}};d.addEventListener("click",S);
//# sourceMappingURL=index.js.map
