import{a as b,i as v,S as h}from"./assets/vendor-CMB7Fqvg.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))o(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const m of s.addedNodes)m.tagName==="LINK"&&m.rel==="modulepreload"&&o(m)}).observe(document,{childList:!0,subtree:!0});function a(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function o(e){if(e.ep)return;e.ep=!0;const s=a(e);fetch(e.href,s)}})();const g=(t,r)=>{const a={params:{q:t,page:r,per_page:15,key:"48292364-ad13d53928d4b39a49844bb07"}};return b.get("https://pixabay.com/api/",a)},y=t=>`
        <li class="gallery-card">
            <a href="${t.largeImageURL}">
                <img src="${t.webformatURL}" alt="${t.tags}"/>
            </a>
            <div class="info">
                <p>Likes: ${t.likes}</p>
                <p>Views: ${t.views}</p>
                <p>Comments: ${t.comments}</p>
                <p>Downloads: ${t.downloads}</p>
            </div>
        </li>`,p=t=>{v.show({title:"❌",message:t,position:"topRight",timeout:3e3})},f=document.querySelector(".form"),l=document.querySelector(".search-list"),c=document.querySelector(".js-btn-load"),d=document.querySelector(".loader");let i=1,n="",u=0;const w=async t=>{if(t.preventDefault(),n=t.currentTarget.elements.search.value.trim(),n===""){p("Enter text to search!");return}i=1,d.classList.add("active"),l.innerHTML="",c.classList.add("is-hidden");try{const{data:r}=await g(n,i);if(r.hits.length===0){p("Sorry, there are no images matching your search query. Please try again!"),f.reset();return}u=r.totalHits;const a=r.hits.map(e=>y(e)).join("");l.innerHTML=a,new h(".gallery-card a",{captionDelay:250,captionsData:"alt"}).refresh(),u>1&&c.classList.remove("is-hidden")}catch(r){console.log(r)}finally{d.classList.remove("active")}};f.addEventListener("submit",w);const L=async()=>{if(i<u)i++,d.classList.add("active");else return;try{const{data:t}=await g(n,i),r=t.hits.map(e=>y(e)).join("");l.insertAdjacentHTML("beforeend",r),new h(".gallery-card a",{captionDelay:250,captionsData:"alt"}).refresh();const o=l.querySelector(".gallery-card");if(o){const e=o.getBoundingClientRect().height;window.scrollBy({top:e*2,behavior:"smooth"})}i>=u&&(c.classList.add("is-hidden"),p("We're sorry, but you've reached the end of search results."),c.removeEventListener("click",L))}catch(t){console.log(t)}finally{d.classList.remove("active")}};c.addEventListener("click",L);
//# sourceMappingURL=index.js.map
