import{a as b,i as v,S as h}from"./assets/vendor-CMB7Fqvg.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))i(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const u of s.addedNodes)u.tagName==="LINK"&&u.rel==="modulepreload"&&i(u)}).observe(document,{childList:!0,subtree:!0});function a(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerPolicy&&(s.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?s.credentials="include":t.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function i(t){if(t.ep)return;t.ep=!0;const s=a(t);fetch(t.href,s)}})();const f=(e,r)=>{const a={params:{q:e,page:r,per_page:15,key:"48292364-ad13d53928d4b39a49844bb07"}};return b.get("https://pixabay.com/api/",a)},y=e=>`
        <li class="gallery-card">
            <a href="${e.largeImageURL}">
                <img src="${e.webformatURL}" alt="${e.tags}"/>
            </a>
            <div class="info">
                <p>Likes: ${e.likes}</p>
                <p>Views: ${e.views}</p>
                <p>Comments: ${e.comments}</p>
                <p>Downloads: ${e.downloads}</p>
            </div>
        </li>`,p=e=>{v.show({title:"❌",message:e,position:"topRight",timeout:3e3})},g=document.querySelector(".form"),m=document.querySelector(".search-list"),c=document.querySelector(".js-btn-load"),l=document.querySelector(".loader");let o=1,n="",d=0;const w=async e=>{if(e.preventDefault(),n=e.currentTarget.elements.search.value.trim(),n===""){p("Enter text to search!");return}o=1,l.classList.add("active"),m.innerHTML="",c.classList.add("is-hidden");try{const{data:r}=await f(n,o);if(r.hits.length===0){p("Sorry, there are no images matching your search query. Please try again!"),g.reset();return}d=r.totalHits;const a=r.hits.map(t=>y(t)).join("");m.innerHTML=a,new h(".gallery-card a",{captionDelay:250,captionsData:"alt"}).refresh(),d>1&&c.classList.remove("is-hidden")}catch(r){console.log(r)}finally{l.classList.remove("active")}};g.addEventListener("submit",w);const L=async()=>{o<d&&(o++,l.classList.add("active"));try{const{data:e}=await f(n,o,15),r=e.hits.map(i=>y(i)).join("");m.insertAdjacentHTML("beforeend",r),new h(".gallery-card a",{captionDelay:250,captionsData:"alt"}).refresh(),o>=d&&(c.classList.add("is-hidden"),p("We're sorry, but you've reached the end of search results."),c.removeEventListener("click",L))}catch(e){console.log(e)}finally{l.classList.remove("active")}};c.addEventListener("click",L);
//# sourceMappingURL=index.js.map
